swagger.application.name=AccountSystem
  # The @ delimiter is used to get za.ac.nwu.ac.repo.za.ac.nwu.ac.logic.config properties from the POM
swagger.application.description=Parent pom providing dependency and plugin management for applications
		built with Maven
swagger.application.version=1.0-SNAPSHOT

spring.application.name=AccountSystem
server.servlet.context-path=/account-system
spring.mvc.servlet.path=/mvc
